### ISSUE TITLE
Unable to create a cluster with continuous K8s release

### ISSUE THREAD

**Issue by innobead** [innobead/kubefire#37]
**Describe the bug**

```console
➜  Downloads kubefire cluster create demo --force
INFO[2020-10-16T03:16:09+08:00] getting the cri-tools release versions info less than/equal to v1.19.3  bootstrapper=kubeadm
INFO[2020-10-16T03:16:09+08:00] getting the latest kube release tool release version info  bootstrapper=kubeadm
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x6bc7b7]

goroutine 1 [running]:
github.com/innobead/kubefire/pkg/config.(*LocalConfigManager).SaveBootstrapperVersions(0xdf3cc0, 0x0, 0x0, 0xc0000a0240, 0x3, 0x4, 0x7, 0x4)
        /home/davidko/github/innobead/kubefire/pkg/config/local.go:125 +0x37
github.com/innobead/kubefire/pkg/bootstrap.GenerateSaveBootstrapperVersions(0xa0f08f, 0x7, 0x7fce083aa2f8, 0xdf3cc0, 0x7fce3052a048, 0xc0000ba620, 0xc0000ba601, 0x199, 0x5, 0x4, ...)
        /home/davidko/github/innobead/kubefire/pkg/bootstrap/bootstrapper.go:135 +0x7e2
github.com/innobead/kubefire/cmd/kubefire/cmd/cluster.glob..func6(0xdb80a0, 0xc000121820, 0x1, 0x2, 0x0, 0x0)
        /home/davidko/github/innobead/kubefire/cmd/kubefire/cmd/cluster/create.go:58 +0x11d
github.com/spf13/cobra.(*Command).execute(0xdb80a0, 0xc000121800, 0x2, 0x2, 0xdb80a0, 0xc000121800)
        /home/davidko/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:831 +0x530
github.com/spf13/cobra.(*Command).ExecuteC(0xdba2c0, 0xc00017bf18, 0x1, 0x1)
        /home/davidko/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/davidko/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /home/davidko/github/innobead/kubefire/cmd/kubefire/kubefire.go:72 +0x13f

```

**To Reproduce**
Steps to reproduce the behavior with debug log enabled. `--log-level=debug`

**Expected behavior**

**Environment**
 - OS version
    - run `cat /etc/os-release`
 - Kubefire version
    - run `kubefire version`
 - Kubefire runtime info
    - run `kubefire info` 

**Additional context**

**Comment by innobead** [comment]
Result

```console
➜  kubefire info -b -o yaml
kubeadm: v1.19.3,v1.18.10,v1.17.13
k3s: v1.16.15,v1.17.12,v1.18.9,v1.19.2
skuba: v1.4.1,v1.3.5

```
