### ISSUE TITLE
Bootstrapping k3s does not work

### ISSUE THREAD

**Issue by imusmanmalik** [innobead/kubefire#50]
**Describe the bug**

When trying to bootstrap a k3s cluster, it ends up with a panic (goroutine)

**To Reproduce**

Execute command

```console
kubefire cluster create demo --bootstrapper=k3s -v v1.22 -l trace
```
Output:

```console
DEBU[2021-12-29T19:49:13Z]       di.go:46   github.com/innobead/kubefire/internal/di.DelayInit() initializing dependency injection system
DEBU[2021-12-29T19:49:13Z]       di.go:119  github.com/innobead/kubefire/internal/di.DelayInit() completed dependency injection system
DEBU[2021-12-29T19:49:13Z]       di.go:42   github.com/innobead/kubefire/internal/di.DelayInit() forcibly reinitializing dependency injection system
DEBU[2021-12-29T19:49:13Z]       di.go:119  github.com/innobead/kubefire/internal/di.DelayInit() completed dependency injection system
DEBU[2021-12-29T19:49:13Z]      k3s.go:69   github.com/innobead/kubefire/pkg/bootstrap/versionfinder.(*K3sVersionFinder).GetLatestVersion() getting the latest released version info      bootstrapper=k3s
DEBU[2021-12-29T19:49:13Z]      k3s.go:28   github.com/innobead/kubefire/pkg/bootstrap/versionfinder.(*K3sVersionFinder).GetVersionsAfterVersion() getting the released versions info            bootstrapper=k3s
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/innobead/kubefire/pkg/bootstrap/versionfinder.(*K3sVersionFinder).GetVersionsAfterVersion(0xc00009cbd0, 0xa0434e, 0x1, 0xa11817, 0x2, 0xa04352, 0x1, 0x0, 0x0, 0xc00053a1d8, ...)
	/home/runner/work/kubefire/kubefire/pkg/bootstrap/versionfinder/k3s.go:47 +0x6e6
github.com/innobead/kubefire/pkg/bootstrap.GenerateSaveBootstrapperVersions(0x7fff3a3c97cb, 0x3, 0x7f6d106203f8, 0xdbfaa8, 0x4, 0x199, 0x9aa560, 0xc0000c65a0, 0x9342e0, 0xc0000c65a0, ...)
	/home/runner/work/kubefire/kubefire/pkg/bootstrap/bootstrapper.go:91 +0x2d5
github.com/innobead/kubefire/cmd/kubefire/cmd/cluster.glob..func6(0xd86460, 0xc000136e40, 0x1, 0x6, 0x0, 0x0)
	/home/runner/work/kubefire/kubefire/cmd/kubefire/cmd/cluster/create.go:61 +0x14a
github.com/spf13/cobra.(*Command).execute(0xd86460, 0xc000136de0, 0x6, 0x6, 0xd86460, 0xc000136de0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:831 +0x523
github.com/spf13/cobra.(*Command).ExecuteC(0xd88680, 0xc00017df18, 0x1, 0x1)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/home/runner/work/kubefire/kubefire/cmd/kubefire/kubefire.go:73 +0x13f
```

or

```console
kubefire cluster create demo --bootstrapper=k3s -l trace
```

Output:
```console
DEBU[2021-12-29T19:53:03Z]       di.go:46   github.com/innobead/kubefire/internal/di.DelayInit() initializing dependency injection system
DEBU[2021-12-29T19:53:03Z]       di.go:119  github.com/innobead/kubefire/internal/di.DelayInit() completed dependency injection system
DEBU[2021-12-29T19:53:03Z]       di.go:42   github.com/innobead/kubefire/internal/di.DelayInit() forcibly reinitializing dependency injection system
DEBU[2021-12-29T19:53:03Z]       di.go:119  github.com/innobead/kubefire/internal/di.DelayInit() completed dependency injection system
DEBU[2021-12-29T19:53:03Z]      k3s.go:69   github.com/innobead/kubefire/pkg/bootstrap/versionfinder.(*K3sVersionFinder).GetLatestVersion() getting the latest released version info      bootstrapper=k3s
DEBU[2021-12-29T19:53:04Z]      k3s.go:28   github.com/innobead/kubefire/pkg/bootstrap/versionfinder.(*K3sVersionFinder).GetVersionsAfterVersion() getting the released versions info            bootstrapper=k3s
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/innobead/kubefire/pkg/bootstrap/versionfinder.(*K3sVersionFinder).GetVersionsAfterVersion(0xc0001eaac0, 0xa0434e, 0x1, 0xa11817, 0x2, 0xa04352, 0x1, 0x0, 0x0, 0xc0000fe0f8, ...)
	/home/runner/work/kubefire/kubefire/pkg/bootstrap/versionfinder/k3s.go:47 +0x6e6
github.com/innobead/kubefire/pkg/bootstrap.GenerateSaveBootstrapperVersions(0x7ffc906fc7d4, 0x3, 0x7f9a6cd3e4e8, 0xdbfaa8, 0x4, 0x199, 0x9aa560, 0xc0001d74a0, 0x9342e0, 0xc0001d74a0, ...)
	/home/runner/work/kubefire/kubefire/pkg/bootstrap/bootstrapper.go:91 +0x2d5
github.com/innobead/kubefire/cmd/kubefire/cmd/cluster.glob..func6(0xd86460, 0xc000166e80, 0x1, 0x4, 0x0, 0x0)
	/home/runner/work/kubefire/kubefire/cmd/kubefire/cmd/cluster/create.go:61 +0x14a
github.com/spf13/cobra.(*Command).execute(0xd86460, 0xc000166e40, 0x4, 0x4, 0xd86460, 0xc000166e40)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:831 +0x523
github.com/spf13/cobra.(*Command).ExecuteC(0xd88680, 0xc00017df18, 0x1, 0x1)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/home/runner/work/kubefire/kubefire/cmd/kubefire/kubefire.go:73 +0x13f
```

**Expected behavior**

Cluster is provisioned using k3s as bootstrap

**Environment**
 - OS version
```console
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
 - Kubefire version
```console
Version: v0.3.6
Build: 9413383-20210502190639
```
 - Kubefire runtime info
```console
CONTAINERD	IGNITE	CNI   	RUNC      	CNIPLUGIN
v1.4.4    	v0.9.0	v0.9.1	1.0.0-rc93	0.4.0/kubefire-cni-bridge
```

**Comment by innobead** [comment]
It seems likely an intermittent error when parsing the versions.

<details>
<summary>log to deploy a 1.22 k3s cluster</summary>
```
❯ kubefire cluster create demo --bootstrapper=k3s -v v1.22 -f
INFO[2022-02-24T18:11:25+08:00] deleting cluster                              cluster=demo force=true
INFO[2022-02-24T18:11:25+08:00] deleting worker nodes                         cluster=demo
INFO[2022-02-24T18:11:25+08:00] deleting node                                 node=demo-worker-1
INFO[2022-02-24T18:11:25+08:00] time="2022-02-24T18:11:25+08:00" level=info msg="Removing the container with ID \"ignite-c02db8ff631f5b01\" from the \"cni\" network"
INFO[2022-02-24T18:11:25+08:00] time="2022-02-24T18:11:25+08:00" level=info msg="Removed VM with name \"demo-worker-1\" and ID \"c02db8ff631f5b01\""
INFO[2022-02-24T18:11:25+08:00] deleting master nodes                         cluster=demo
INFO[2022-02-24T18:11:25+08:00] deleting node                                 node=demo-master-1
INFO[2022-02-24T18:11:25+08:00] time="2022-02-24T18:11:25+08:00" level=info msg="Removing the container with ID \"ignite-8006791bbbb4bc7c\" from the \"cni\" network"
INFO[2022-02-24T18:11:26+08:00] time="2022-02-24T18:11:26+08:00" level=info msg="Removed VM with name \"demo-master-1\" and ID \"8006791bbbb4bc7c\""
INFO[2022-02-24T18:11:26+08:00] deleting cluster configurations               cluster=demo
INFO[2022-02-24T18:11:26+08:00] initializing cluster configuration            cluster=demo
INFO[2022-02-24T18:11:26+08:00] saving cluster configurations                 cluster=demo
INFO[2022-02-24T18:11:26+08:00] creating cluster                              cluster=demo
INFO[2022-02-24T18:11:26+08:00] creating master nodes of cluster              cluster=demo started=true
INFO[2022-02-24T18:11:26+08:00] creating node                                 node=demo-master-1
INFO[2022-02-24T18:11:27+08:00] time="2022-02-24T18:11:27+08:00" level=info msg="Created VM with ID \"08917c2c639dca2e\" and name \"demo-master-1\""
INFO[2022-02-24T18:11:28+08:00] time="2022-02-24T18:11:28+08:00" level=info msg="Networking is handled by \"cni\""
time="2022-02-24T18:11:28+08:00" level=info msg="Started Firecracker VM \"08917c2c639dca2e\" in a container with ID \"ignite-08917c2c639dca2e\""
INFO[2022-02-24T18:11:29+08:00] waiting nodes of cluster running              cluster=demo
INFO[2022-02-24T18:11:29+08:00] initializing cluster nodes                    cluster=demo
INFO[2022-02-24T18:11:29+08:00] initializing node                             node=demo-master-1
INFO[2022-02-24T18:11:29+08:00] waiting all nodes initialization finished
INFO[2022-02-24T18:11:40+08:00] running swapoff -a                            node=demo-master-1
INFO[2022-02-24T18:11:40+08:00] running curl -sfSLO https://raw.githubusercontent.com/innobead/kubefire/v0.3.6/scripts/install-prerequisites-k3s.sh  node=demo-master-1
INFO[2022-02-24T18:11:41+08:00] running chmod +x install-prerequisites-k3s.sh  node=demo-master-1
INFO[2022-02-24T18:11:41+08:00] running  K3S_VERSION=v1.22.6+k3s1 INSTALL_K3S_VERSION=v1.22.6+k3s1 ./install-prerequisites-k3s.sh  node=demo-master-1
INFO[2022-02-24T18:11:41+08:00] 10.62.0.4:22: + TMP_DIR=/tmp/kubefire
+ K3S_VERSION=v1.22.6+k3s1
INFO[2022-02-24T18:11:41+08:00] 10.62.0.4:22: + '[' -z v1.22.6+k3s1 ']'
INFO[2022-02-24T18:11:41+08:00] 10.62.0.4:22: + rm -rf /tmp/kubefire
INFO[2022-02-24T18:11:41+08:00] 10.62.0.4:22: + mkdir -p /tmp/kubefire
INFO[2022-02-24T18:11:41+08:00] 10.62.0.4:22: /tmp/kubefire ~
INFO[2022-02-24T18:11:41+08:00] 10.62.0.4:22: + pushd /tmp/kubefire
INFO[2022-02-24T18:11:41+08:00] 10.62.0.4:22: + trap cleanup EXIT ERR INT TERM
INFO[2022-02-24T18:11:41+08:00] 10.62.0.4:22: + install_k3s
+ local url=https://raw.githubusercontent.com/k3s-io/k3s/v1.22.6+k3s1+k3s1/install.sh
+ [[ v1.22.6+k3s1 =~ .*+k3s.* ]]
+ local url=https://raw.githubusercontent.com/k3s-io/k3s/v1.22.6+k3s1/install.sh
+ curl -sfSL https://raw.githubusercontent.com/k3s-io/k3s/v1.22.6+k3s1/install.sh -o k3s-install.sh
INFO[2022-02-24T18:11:41+08:00] 10.62.0.4:22: + chmod +x k3s-install.sh
INFO[2022-02-24T18:11:41+08:00] 10.62.0.4:22: + sudo mv k3s-install.sh /usr/local/bin/
INFO[2022-02-24T18:11:41+08:00] 10.62.0.4:22: + cleanup
+ rm -rf /tmp/kubefire
INFO[2022-02-24T18:11:41+08:00] 10.62.0.4:22: ~
INFO[2022-02-24T18:11:41+08:00] 10.62.0.4:22: + popd
INFO[2022-02-24T18:11:41+08:00] bootstrapping the first master node           node=demo-master-1
INFO[2022-02-24T18:11:41+08:00] running  K3S_VERSION=v1.22.6+k3s1 INSTALL_K3S_VERSION=v1.22.6+k3s1 INSTALL_K3S_EXEC="--bind-address=10.62.0.4" K3S_VERSION=v1.22.6+k3s1 INSTALL_K3S_VERSION=v1.22.6+k3s1 k3s-install.sh   node=demo-master-1
INFO[2022-02-24T18:11:42+08:00] 10.62.0.4:22: [INFO]  Using v1.22.6+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.22.6+k3s1/sha256sum-amd64.txt
INFO[2022-02-24T18:11:43+08:00] 10.62.0.4:22: [INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.22.6+k3s1/k3s
INFO[2022-02-24T18:11:51+08:00] 10.62.0.4:22: [INFO]  Verifying binary download
INFO[2022-02-24T18:11:51+08:00] 10.62.0.4:22: [INFO]  Installing k3s to /usr/local/bin/k3s
INFO[2022-02-24T18:11:51+08:00] 10.62.0.4:22: [INFO]  Creating /usr/local/bin/kubectl symlink to k3s
INFO[2022-02-24T18:11:51+08:00] 10.62.0.4:22: [INFO]  Creating /usr/local/bin/crictl symlink to k3s
INFO[2022-02-24T18:11:51+08:00] 10.62.0.4:22: [INFO]  Creating /usr/local/bin/ctr symlink to k3s
INFO[2022-02-24T18:11:51+08:00] 10.62.0.4:22: [INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
INFO[2022-02-24T18:11:51+08:00] 10.62.0.4:22: [INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
INFO[2022-02-24T18:11:51+08:00] 10.62.0.4:22: [INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
INFO[2022-02-24T18:11:51+08:00] 10.62.0.4:22: [INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
INFO[2022-02-24T18:11:51+08:00] 10.62.0.4:22: [INFO]  systemd: Enabling k3s unit
INFO[2022-02-24T18:11:51+08:00] 10.62.0.4:22: Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service -> /etc/systemd/system/k3s.service.
INFO[2022-02-24T18:11:52+08:00] 10.62.0.4:22: [INFO]  systemd: Starting k3s
INFO[2022-02-24T18:12:10+08:00] running cat /var/lib/rancher/k3s/server/node-token  node=demo-master-1
INFO[2022-02-24T18:12:10+08:00] saving cluster configurations                 cluster=demo
INFO[2022-02-24T18:12:10+08:00] downloading the kubeconfig of cluster (demo)
INFO[2022-02-24T18:12:10+08:00] saved the kubeconfig of cluster (demo) to /home/davidko/.kubefire/clusters/demo/admin.conf
❯ export `kubefire cluster env demo`
❯ kubectl get nodes
NAME               STATUS   ROLES                  AGE   VERSION
08917c2c639dca2e   Ready    control-plane,master   36s   v1.22.6+k3s1
```
</details>

**Comment by imusmanmalik** [comment]
Seems to be working now, thanks!
